var kingWhite = '<p>♕</p>'
var queenWhite = '<p>♔</p>'
var bishopWhite = '<p>♗</p>'
var castleWhite = '<p>♖</p>'
var knightWhite = '<p>♘</p>'
var pawnWhite = '<p>♙</p>'

var kingBlack = '<p>♕</p>'
var queenBlack = '<p>♔</p>'
var bishopBlack = '<p>♗</p>'
var castleBlack = '<p>♖</p>'
var knightBlack = '<p>♘</p>'
var pawnBlack = '<p>♙</p>'